# Generated by Django 5.1.1 on 2024-10-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionare', '0003_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_choice',
            new_name='choice',
        ),
    ]
